apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/build-enable-automatic-updates: 'false'
    run.googleapis.com/build-id: 05bb0c13-348f-4678-8a25-d77f4f62b4f2
    run.googleapis.com/build-image-uri: us-central1-docker.pkg.dev/diesel-media-485505-e2/cloud-run-source-deploy/gentle-path-api
    run.googleapis.com/build-name: projects/883951071472/locations/us-central1/builds/05bb0c13-348f-4678-8a25-d77f4f62b4f2
    run.googleapis.com/build-source-location: gs://run-sources-diesel-media-485505-e2-us-central1/services/gentle-path-api/1769828733.332736-25a1f83f367943a3bb466e9fa0699c3e.zip#1769828732902101
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/maxScale: '20'
    run.googleapis.com/urls: '["https://gentle-path-api-883951071472.us-central1.run.app","https://gentle-path-api-7kxt2grk6q-uc.a.run.app"]'
  labels:
    cloud.googleapis.com/location: us-central1
    commit-sha: bc16b329a6540c0c0ae456e4a47d0403ab634085
    gcb-build-id: a38bc56c-3830-4411-a3c4-b817a26f9abb
    gcb-trigger-id: a3c2113e-5d81-4cbc-99a1-5294370e4421
    gcb-trigger-region: global
    managed-by: gcp-cloud-build-deploy-cloud-run
  name: gentle-path-api
  namespace: '883951071472'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '20'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 553.0.0
        run.googleapis.com/cloudsql-instances: diesel-media-485505-e2:us-central1:gentle-path-db
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: cbaeeebwaa
        commit-sha: bc16b329a6540c0c0ae456e4a47d0403ab634085
        gcb-build-id: a38bc56c-3830-4411-a3c4-b817a26f9abb
        gcb-trigger-id: a3c2113e-5d81-4cbc-99a1-5294370e4421
        gcb-trigger-region: global
        managed-by: gcp-cloud-build-deploy-cloud-run
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: FIREBASE_ADMIN_JSON
          valueFrom:
            secretKeyRef:
              key: latest
              name: firebase-admin-json
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: latest
              name: db-password
        - name: SUPPORT_TO_EMAIL
          value: cloud.backend26@gmail.com
        - name: SUPPORT_SMTP_HOST
          value: smtp.gmail.com
        - name: SUPPORT_SMTP_PORT
          value: '587'
        - name: SUPPORT_SMTP_USER
          value: cloud.backend26@gmail.com
        - name: SUPPORT_FROM_EMAIL
          value: cloud.backend26@gmail.com
        - name: DB_HOST
          value: /cloudsql/diesel-media-485505-e2:us-central1:gentle-path-db
        - name: DB_PORT
          value: '5432'
        - name: DB_NAME
          value: gentle_path
        - name: DB_USER
          value: gentle_app
        - name: SUPPORT_SMTP_PASS
          valueFrom:
            secretKeyRef:
              key: latest
              name: support-smtp-pass
        - name: UPLOADS_DRIVER
          value: gcs
        - name: UPLOADS_BUCKET
          value: gentle-path-uploads-diesel-media-485505-e2
        image: us-central1-docker.pkg.dev/diesel-media-485505-e2/gentle-path-repo/gentle-path-backend:latest
        name: gentle-path-api-1
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      serviceAccountName: 883951071472-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
